// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiq2Qv6ytzNuRVvEVc04Fy4D2WQMTSk-w',
    appId: '1:783347677318:web:d89cc129fdbd84823cf907',
    messagingSenderId: '783347677318',
    projectId: 'hangover-auth',
    authDomain: 'hangover-auth.firebaseapp.com',
    storageBucket: 'hangover-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDTED87MmqB5i3gOMhpxoEG0R0cFT6JN8',
    appId: '1:783347677318:android:b532f0719bcb3cfe3cf907',
    messagingSenderId: '783347677318',
    projectId: 'hangover-auth',
    storageBucket: 'hangover-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0NeUySxJBkjFOwcMlSfJS6j0K_PlbqyU',
    appId: '1:783347677318:ios:cb3bb78c3e4249e93cf907',
    messagingSenderId: '783347677318',
    projectId: 'hangover-auth',
    storageBucket: 'hangover-auth.appspot.com',
    iosClientId: '783347677318-l8399d82hud1277v1143ck881ifdcok7.apps.googleusercontent.com',
    iosBundleId: 'com.example.hangover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0NeUySxJBkjFOwcMlSfJS6j0K_PlbqyU',
    appId: '1:783347677318:ios:0de88942271d5de03cf907',
    messagingSenderId: '783347677318',
    projectId: 'hangover-auth',
    storageBucket: 'hangover-auth.appspot.com',
    iosClientId: '783347677318-aeih4rirjoc4k9erl25q9u28d3bb6g3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.hangover.RunnerTests',
  );
}
